# AI Research Agent Docker Compose Configuration

services:
  backend:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: ai-research-backend
    ports:
      - "5001:5000"
    environment:
      - PORT=5000
      - FLASK_DEBUG=0
      - CORS_ORIGINS=http://localhost:3000
    volumes:
      - ./.env:/app/.env:ro
      - ./outputs:/app/outputs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - REACT_APP_API_URL=http://localhost:5001
    container_name: ai-research-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5001
    restart: unless-stopped